linkPrefix = "/doxity-demo"
compiler = "0.4.2+commit.af6afb04.Darwin.appleclang"
name = "doxity-demo"
license = "MIT"
version = "0.0.1"
description = "Solidity Documentation Generator"
homepage = "https://github.com/hitchcott/doxity-demo"
author = "Chris Hitchcott"
buildTime = 2016-10-28T21:47:57.090Z